language: c

os:
  - linux

arch:
  - s390x
  - amd64

compiler:
  - gcc
  - clang

script:
  - sudo gcc -o be be.c
  - sudo ./be
  - sudo apt-get install build-essential
  - cd "$TRAVIS_BUILD_DIR"
  - sudo sh do

install: skip
