language: c

os:
  - linux
  - osx

arch:
  - amd64
  - s390x

compiler:
  - gcc
  - clang

script:
  - cd "$TRAVIS_BUILD_DIR"
  - make

after_success:
  - cd "$TRAVIS_BUILD_DIR"
  - ./endiantest

install: skip
